version: '3'
services:
  strapi:
    image: strapi/strapi:3.6.8
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: ${MYSQL_PORT}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --secure-file-priv ""
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql-files/:/var/lib/mysql-files/
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
